# This is a docker-compose file for starting
# only the database Postgres and PgAdmin4

# docker-compose -f ./postgres.yaml up

version: "3.3"

services:

  # Pgadmin is the most popular and feature rich Open Source administration 
  # and development platform for PostgreSQL
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: db@db.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped

  # PostgreSQL (postgres) the most advanced Open Source database in the world.
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: journalism
      PGDATA: /var/lib/postgresql/data
    networks:
      - webnet

# Creating volume with local driver
volumes:

  postgres:
    driver: local

  pgadmin:
    driver: local

# Creating network with driver "bridge"
networks:
  webnet:
    driver: bridge
